/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StepType = IDL.Variant({ 'hajj' : IDL.Null, 'umrah' : IDL.Null });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const RitualStep = IDL.Record({
  'day' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'stepType' : StepType,
  'duaId' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Dua = IDL.Record({
  'id' : IDL.Nat,
  'hindiMeaning' : IDL.Text,
  'hindiTransliteration' : IDL.Text,
  'name' : IDL.Text,
  'arabic' : IDL.Text,
  'category' : StepType,
});
export const PdfFlipbook = IDL.Record({
  'url' : ExternalBlob,
  'name' : IDL.Text,
  'pageCount' : IDL.Nat,
});
export const UserProgress = IDL.Record({
  'completedUmrahSteps' : IDL.Vec(IDL.Nat),
  'completedHajjSteps' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDua' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, StepType],
      [IDL.Nat],
      [],
    ),
  'addFlipbook' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
  'addRitualStep' : IDL.Func([RitualStep], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDuas' : IDL.Func([], [IDL.Vec(Dua)], ['query']),
  'getAllFlipbooks' : IDL.Func([], [IDL.Vec(PdfFlipbook)], ['query']),
  'getAllRitualSteps' : IDL.Func([], [IDL.Vec(RitualStep)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDua' : IDL.Func([IDL.Nat], [IDL.Opt(Dua)], ['query']),
  'getFlipbook' : IDL.Func([IDL.Text], [IDL.Opt(PdfFlipbook)], ['query']),
  'getRitualStep' : IDL.Func([IDL.Nat], [IDL.Opt(RitualStep)], ['query']),
  'getUserProgress' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProgress)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchDuasByCategory' : IDL.Func([StepType], [IDL.Vec(Dua)], ['query']),
  'searchRitualStepsByType' : IDL.Func(
      [StepType],
      [IDL.Vec(RitualStep)],
      ['query'],
    ),
  'updateUserProgress' : IDL.Func([UserProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StepType = IDL.Variant({ 'hajj' : IDL.Null, 'umrah' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const RitualStep = IDL.Record({
    'day' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'stepType' : StepType,
    'duaId' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Dua = IDL.Record({
    'id' : IDL.Nat,
    'hindiMeaning' : IDL.Text,
    'hindiTransliteration' : IDL.Text,
    'name' : IDL.Text,
    'arabic' : IDL.Text,
    'category' : StepType,
  });
  const PdfFlipbook = IDL.Record({
    'url' : ExternalBlob,
    'name' : IDL.Text,
    'pageCount' : IDL.Nat,
  });
  const UserProgress = IDL.Record({
    'completedUmrahSteps' : IDL.Vec(IDL.Nat),
    'completedHajjSteps' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDua' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, StepType],
        [IDL.Nat],
        [],
      ),
    'addFlipbook' : IDL.Func([IDL.Text, ExternalBlob, IDL.Nat], [], []),
    'addRitualStep' : IDL.Func([RitualStep], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDuas' : IDL.Func([], [IDL.Vec(Dua)], ['query']),
    'getAllFlipbooks' : IDL.Func([], [IDL.Vec(PdfFlipbook)], ['query']),
    'getAllRitualSteps' : IDL.Func([], [IDL.Vec(RitualStep)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDua' : IDL.Func([IDL.Nat], [IDL.Opt(Dua)], ['query']),
    'getFlipbook' : IDL.Func([IDL.Text], [IDL.Opt(PdfFlipbook)], ['query']),
    'getRitualStep' : IDL.Func([IDL.Nat], [IDL.Opt(RitualStep)], ['query']),
    'getUserProgress' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProgress)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchDuasByCategory' : IDL.Func([StepType], [IDL.Vec(Dua)], ['query']),
    'searchRitualStepsByType' : IDL.Func(
        [StepType],
        [IDL.Vec(RitualStep)],
        ['query'],
      ),
    'updateUserProgress' : IDL.Func([UserProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };