/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Dua {
  'id' : bigint,
  'hindiMeaning' : string,
  'hindiTransliteration' : string,
  'name' : string,
  'arabic' : string,
  'category' : StepType,
}
export type ExternalBlob = Uint8Array;
export interface PdfFlipbook {
  'url' : ExternalBlob,
  'name' : string,
  'pageCount' : bigint,
}
export interface RitualStep {
  'day' : [] | [bigint],
  'title' : string,
  'icon' : string,
  'description' : string,
  'stepNumber' : bigint,
  'stepType' : StepType,
  'duaId' : [] | [bigint],
}
export type StepType = { 'hajj' : null } |
  { 'umrah' : null };
export interface UserProgress {
  'completedUmrahSteps' : Array<bigint>,
  'completedHajjSteps' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDua' : ActorMethod<[string, string, string, string, StepType], bigint>,
  'addFlipbook' : ActorMethod<[string, ExternalBlob, bigint], undefined>,
  'addRitualStep' : ActorMethod<[RitualStep], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDuas' : ActorMethod<[], Array<Dua>>,
  'getAllFlipbooks' : ActorMethod<[], Array<PdfFlipbook>>,
  'getAllRitualSteps' : ActorMethod<[], Array<RitualStep>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDua' : ActorMethod<[bigint], [] | [Dua]>,
  'getFlipbook' : ActorMethod<[string], [] | [PdfFlipbook]>,
  'getRitualStep' : ActorMethod<[bigint], [] | [RitualStep]>,
  'getUserProgress' : ActorMethod<[Principal], [] | [UserProgress]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchDuasByCategory' : ActorMethod<[StepType], Array<Dua>>,
  'searchRitualStepsByType' : ActorMethod<[StepType], Array<RitualStep>>,
  'updateUserProgress' : ActorMethod<[UserProgress], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];